//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PrinterHub.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PRINTERHUB_FORM             101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PrinterHubTYPE              130
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG1                     317
#define IDD_DIALOG_ADD_PRINTER          1000
#define IDD_DIALOG_FIRMWARE_PROGRESS    1002
#define IDD_DIALOG_ABOUT                1003
#define IDD_DIALOG_SETTINGS             1004
#define IDD_DIALOG_TICKET_DETAIL        1005
#define IDC_LIST_PRINTERS               2000
#define IDC_LIST_FIRMWARE_QUEUE         2001
#define IDC_LIST_TICKETS                2002
#define IDC_LIST_FIRMWARE_HISTORY       2003
#define IDC_LIST1                       2004
#define IDC_LIST2                       2005
#define IDC_LIST3                       2006
#define IDC_BUTTON_PRINTER_ADD_PRINTER  2100
#define IDC_BUTTON_PRINTER_EDIT_PRINTER 2101
#define IDC_BUTTON_PRINTER_DELETE_PRINTER 2102
#define IDC_BUTTON_PRINTER_UNDO         2103
#define IDC_BUTTON_PRINTER_REDO         2104
#define IDC_BUTTON_PRINTER_UPDATE_FIRMWARE 2105
#define IDC_BUTTON_PRINTER_REFRESH      2106
#define IDC_BUTTON_PRINTER_IMPORT       2107
#define IDC_BUTTON_PRINTER_EXPORT       2108
#define IDC_BUTTON_FIRMWARE_ADD_TO_QUEUE 2200
#define IDC_BUTTON_FIRMWARE_PROCESS_QUEUE 2201
#define IDC_BUTTON_FIRMWARE_CANCEL_JOB  2202
#define IDC_BUTTON_FIRMWARE_VIEW_LOG    2203
#define IDC_BUTTON_FIRMWARE_REFRESH     2204
#define IDC_                            2204
#define IDC_BUTTON_ADD_TO_QUEUE         2210
#define IDC_BUTTON_VIEW_LOG             2211
#define IDC_BUTTON_TICKET_NEW_TICKET    2300
#define IDC_BUTTON_TICKET_CLOSE_TICKET  2301
#define IDC_BUTTON_TICKET_REMOVE        2302
#define IDC_BUTTON_TICKET_REOPEN        2303
#define IDC_BUTTON_TICKET_REFRESH       2304
#define IDC_EDIT_ADD_PRINTER_ID         3000
#define IDC_EDIT_ADD_PRINTER_MODEL      3001
#define IDC_EDIT_ADD_PRINTER_BRAND      3002
#define IDC_EDIT_ADD_PRINTER_STATUS     3003
#define IDC_EDIT_ADD_PRINTER_DATE       3004
#define IDC_EDIT_ADD_PRINTER_WARRANTY   3005
#define IDC_BUTTON_ADD_CONTINUE         3006
#define IDC_COMBO_FIRMWARE_VERSION      3100
#define IDC_STATIC_PRINTER_INFO         3101
#define IDC_STATIC_CURRENT_VERSION      3102
#define IDC_STATIC_NEW_VERSION          3103
#define IDC_STATIC_DESCRIPTION          3107
#define IDC_PROGRESS_FIRMWARE           3108
#define IDC_STATIC_PROGRESS_STATUS      3109
#define IDC_BUTTON_DOWNLOAD_FIRMWARE    3110
#define IDC_BUTTON_BROWSE_FIRMWARE      3111
#define IDS_APP_TITLE                   4000
#define IDS_EMPTY_ID_ERROR              4001
#define IDS_DUPLICATE_ID_ERROR          4002
#define IDS_INVALID_CHARACTER_ERROR     4003
#define IDS_EMPTY_MODEL_ERROR           4004
#define IDS_INVALID_WARRANTY_ERROR      4005
#define IDS_PRINTER_ADDED_SUCCESS       4006
#define IDS_PRINTER_UPDATED_SUCCESS     4007
#define IDS_PRINTER_DELETED_SUCCESS     4008
#define IDS_FIRMWARE_UPDATE_START       4009
#define IDS_FIRMWARE_UPDATE_SUCCESS     4010
#define IDS_FIRMWARE_UPDATE_FAILED      4011
#define IDS_TICKET_CREATED_SUCCESS      4012
#define IDS_TICKET_CLOSED_SUCCESS       4013
#define IDI_APP_ICON                    5000
#define IDI_PRINTER_ICON                5001
#define IDI_FIRMWARE_ICON               5002
#define IDI_TICKET_ICON                 5003
#define IDI_WARNING_ICON                5004
#define IDI_SUCCESS_ICON                5005
#define IDI_ERROR_ICON                  5006
#define IDB_TOOLBAR_PRINTER             5100
#define IDB_TOOLBAR_FIRMWARE            5101
#define IDB_TOOLBAR_TICKET              5102
#define IDM_FILE_NEW                    32768
#define IDM_FILE_OPEN                   32769
#define IDM_FILE_SAVE                   32770
#define IDM_FILE_SAVE_AS                32771
#define IDM_FILE_IMPORT                 32772
#define IDM_FILE_EXPORT                 32773
#define IDM_FILE_PRINT                  32774
#define IDM_FILE_PRINT_PREVIEW          32775
#define IDM_FILE_EXIT                   32776
#define IDM_EDIT_ADD                    32777
#define IDM_EDIT_EDIT                   32778
#define IDM_EDIT_DELETE                 32779
#define IDM_EDIT_UNDO                   32780
#define IDM_EDIT_REDO                   32781
#define IDM_EDIT_COPY                   32782
#define IDM_EDIT_PASTE                  32783
#define IDM_VIEW_TOOLBAR                32784
#define IDM_VIEW_STATUS_BAR             32785
#define IDM_VIEW_REFRESH                32786
#define IDM_FIRMWARE_ADD                32787
#define IDM_FIRMWARE_PROCESS            32788
#define IDM_FIRMWARE_CANCEL             32789
#define IDM_FIRMWARE_VIEW_LOG           32790
#define IDM_TICKET_NEW                  32791
#define IDM_TICKET_CLOSE                32792
#define IDM_TICKET_REOPEN               32793
#define IDM_TICKET_DELETE               32794
#define IDM_HELP_ABOUT                  32799
#define IDM_HELP_USER_GUIDE             32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
